name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
      
      - name: Install package and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
          fqdn: yacd.kuwi.net
          git_config_name: GitHub Actions
          git_config_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages-content
      
      - name: Create gh-pages.zip with top-level directory
        run: |
          mkdir -p temp/gh-pages
          cp -r gh-pages-content/* temp/gh-pages/
          cd temp
          zip -r ../gh-pages.zip . -x "*/.git*"
          ls -la ../gh-pages.zip
      
      - name: Delete existing gh-pages.zip from release
        run: |
          release=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.8.8")
          asset_id=$(echo "$release" | jq -r '.assets[] | select(.name == "gh-pages.zip") | .id')
          if [ "$asset_id" != "null" ] && [ -n "$asset_id" ]; then
            echo "Deleting existing gh-pages.zip with asset ID: $asset_id"
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id"
          else
            echo "No existing gh-pages.zip found in release"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload new gh-pages.zip to Release v1.8.8
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.8.8
          files: ./gh-pages.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}